// Settings Actions
// TODO: Split for individual settings
export const SETTINGS_FETCH_REQUESTED = 'SETTINGS_FETCH_REQUESTED';
export const SETTINGS_FETCH_SUCCEEDED = 'SETTINGS_FETCH_SUCCEEDED';
export const SETTINGS_FETCH_FAILED = 'SETTINGS_FETCH_FAILED';

export const SETTINGS_PUT_REQUESTED = 'SETTINGS_PUT_REQUESTED';
export const SETTINGS_PUT_SUCCEEDED = 'SETTINGS_PUT_SUCCEEDED';
export const SETTINGS_PUT_FAILED = 'SETTINGS_PUT_FAILED';

// TBA Actions
// TODO: Split fetches for matches and lists of matches
export const TBA_FETCH_TEAM_LIST = 'TBA_FETCH_TEAM_LIST';
export const TBA_RECEIVE_TEAM_LIST = 'TBA_RECEIVE_TEAM_LIST';
export const TBA_FETCH_MATCH_DATA = 'TBA_FETCH_MATCH_DATA';
export const TBA_RECEIVE_MATCH_DATA = 'TBA_RECEIVE_MATCH_DATA';

// Scouting Page Actions
export const SUBMIT_SCOUTING_DATA = 'SUBMIT_SCOUTING_DATA';
export const SUBMITTED_SCOUTING_DATA = 'SUBMITTED_SCOUTING_DATA';

// Test Data Actions
export const DB_FETCH_TEST_DATA = 'DB_FETCH_TEST_DATA';
export const DB_RECEIVE_TEST_DATA = 'DB_RECEIVE_TEST_DATA';

// User Data Actions
export const DB_FETCH_USER_DATA = 'DB_FETCH_USER_DATA';
export const DB_RECEIVE_USER_DATA = 'DB_RECEIVE_USER_DATA';
export const DB_FETCH_USER_LIST = 'DB_FETCH_USER_LIST';
export const DB_RECEIVE_USER_LIST = 'DB_RECEIVE_USER_LIST';

// Team Data Actions
export const DB_FETCH_TEAM_DATA = 'DB_FETCH_TEAM_DATA';
export const DB_RECEIVE_TEAM_DATA = 'DB_RECEIVE_TEAM_DATA';
export const DB_FETCH_TEAM_LIST = 'DB_FETCH_TEAM_LIST';
export const DB_RECEIVE_TEAM_LIST = 'DB_RECEIVE_TEAM_LIST';

// Match Data Actions
export const DB_FETCH_MATCH_DATA = 'DB_FETCH_MATCH_DATA';
export const DB_RECEIVE_MATCH_DATA = 'DB_RECEIVE_MATCH_DATA';
export const DB_FETCH_MATCH_LIST = 'DB_FETCH_MATCH_LIST';
export const DB_RECEIVE_MATCH_LIST = 'DB_RECEIVE_MATCH_LIST';

// Data Data Actions
export const DB_FETCH_DATA_DATA = 'DB_FETCH_DATA_DATA';
export const DB_RECEIVE_DATA_DATA = 'DB_RECEIVE_DATA_DATA';
export const DB_FETCH_DATA_LIST = 'DB_FETCH_DATA_LIST';
export const DB_RECEIVE_DATA_LIST = 'DB_RECEIVE_DATA_LIST';

// Not technically an action...
export const DB_AUTH_TOKEN = 'Y2hhb3MyMDE4c2NvdXRpbmc6Y2hhb3MyMDE4c2NvdXRpbmc=';
export const TBA_AUTH_TOKEN_V3 = 'HYXC2ETa0hkDvIF1dV6veZr5gqK2pybJJw4jvMUsJ93GuutRJsWzO4MvfM95opit';
